---
Name: silverware-admin
---

# Configure Admin Extensions:

SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverWare\Admin\Extensions\LeftAndMainExtension
  extra_requirements_css:
    - "silverware/admin: client/dist/styles/bundle.css"
